name: CI
on:
  push:
    branches:
      - main
      
jobs:
  build_fastlane:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Install bundler & Fastlane  
        run: |
          gem install bundler:2.2.27
          bundle config path vendor/bundle
          bundle init
          bundle install --jobs 4 --retry 3       
      - name: Run Fastlane for slack
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: slack_ios
          subdirectory: ios
      # - name: Install Firebase app distribution plugin
      #   run: fastlane add_plugin firebase_app_distribution
      # - name: Upgrade build version
      #   run: bundle exec fastlane slack

      
      
        

  
  
  
     
  
