# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "iOS slack message"
    lane :slack_ios do
        slack(
            message: "iOS app successfully uploaded.",
            success: true,
            slack_url: "https://hooks.slack.com/services/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"
        )
    end
end


